server:
  port: 80

access_token:
  validity_period: 3600

resource:
  id: auth-service

spring:
  datasource:
    url: jdbc:postgresql://database/users
    username: postgresql
    password: postgresql
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true